# Generated by Django 5.2 on 2025-04-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(max_length=500, verbose_name='Описании категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото категории')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='Текст')),
                ('estimation', models.CharField(choices=[('bad', 'плохо'), ('good', 'хорошо'), ('excellent', 'отлично')], default='good', max_length=15, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.TextField(max_length=50, verbose_name='Рабочие дни')),
                ('rest_days', models.TextField(max_length=50, verbose_name='Выходные дни')),
                ('start_time', models.DateTimeField(verbose_name='Начало работы')),
                ('end_time', models.DateTimeField(verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=300, verbose_name='Описание услуги')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('location', models.TextField(max_length=100, verbose_name='Адрес')),
                ('contact', models.IntegerField(verbose_name='Контакты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Лого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.categories', verbose_name='Категории')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.reviews', verbose_name='Рейтинг')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.schedules', verbose_name='График работы')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.services', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
    ]
