# Generated by Django 5.2 on 2025-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
    ]
