# Generated by Django 5.2 on 2025-04-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_app', '0001_initial'),
        ('doctors_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclinic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='scheduleclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_schedules', to='clinic_app.clinic'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic_app.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='doctors_app.doctor', verbose_name='Врачи'),
        ),
        migrations.AddField(
            model_name='scheduleclinic',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.weekday', verbose_name='День недели'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['rating'], name='clinic_app__rating_a89512_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['created_at'], name='clinic_app__created_2f7f01_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_verified'], name='clinic_app__is_veri_c89451_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='clinic_app__is_acti_541f91_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewclinic',
            index=models.Index(fields=['created_at'], name='clinic_app__created_dd7808_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewclinic',
            index=models.Index(fields=['updated_at'], name='clinic_app__updated_0844d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewclinic',
            unique_together={('user', 'clinic')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='clinic_app__created_c7fa95_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['updated_at'], name='clinic_app__updated_0b178a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('clinic', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleclinic',
            unique_together={('clinic', 'weekday')},
        ),
    ]
