# Generated by Django 5.2 on 2025-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_rename_review_reviews_rename_schedule_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinics',
            options={'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описании категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='location',
            field=models.TextField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='rest_days',
            field=models.TextField(max_length=50, verbose_name='Выходные дни'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='work_days',
            field=models.TextField(max_length=50, verbose_name='Рабочие дни'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
