# Generated by Django 5.2 on 2025-04-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_clinics_options_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.categories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.reviews', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.schedules', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.services', verbose_name='Услуги'),
        ),
    ]
