services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - digital_med_network
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - digital_med_network

  web:
    build:
      context: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -- ./wait-for-it.sh redis:6379 -- 
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 digital_med.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - digital_med_network

  celery:
    build:
      context: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -- ./wait-for-it.sh redis:6379 --
              celery -A digital_med worker --loglevel=info"
    volumes:
      - .:/app
    networks:
      - digital_med_network

  celery_beat:
    build:
      context: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -- ./wait-for-it.sh redis:6379 -- 
             celery -A digital_med beat --loglevel=info"
    volumes:
      - .:/app
    networks:
      - digital_med_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  digital_med_network:
    driver: bridge
