# Generated by Django 5.2 on 2025-04-09 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_app', '0002_initial'),
        ('doctors_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(related_name='doctors', to='clinic_app.clinic', verbose_name='Клиники'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors_app.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='reviewdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors_app.doctor', verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='reviewdoctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='scheduledoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docotr_schedules', to='doctors_app.doctor'),
        ),
        migrations.AddField(
            model_name='scheduledoctor',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.weekday', verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.specialization', verbose_name='Специализация'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='doctors_app_date_1f57ac_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='doctors_app_status_5d70a4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='doctors_app_created_ced9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['updated_at'], name='doctors_app_updated_740c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdoctor',
            index=models.Index(fields=['created_at'], name='doctors_app_created_d8c4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdoctor',
            index=models.Index(fields=['updated_at'], name='doctors_app_updated_5d5248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewdoctor',
            unique_together={('user', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduledoctor',
            unique_together={('doctor', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['created_at'], name='doctors_app_created_58d76b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['updated_at'], name='doctors_app_updated_b2c61e_idx'),
        ),
    ]
