# Generated by Django 5.2 on 2025-04-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='doctors_app.doctor'),
        ),
    ]
